//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSensor.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SensorEntities : DbContext
    {
        public SensorEntities()
            : base("name=SensorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Pais> Pais { get; set; }
        public virtual DbSet<Regiao> Regiao { get; set; }
        public virtual DbSet<Sensor> Sensor { get; set; }
        public virtual DbSet<Sensor_valor> Sensor_valor { get; set; }
    }
}
