//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSensor.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sensor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sensor()
        {
            this.Sensor_valor = new HashSet<Sensor_valor>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public Nullable<int> idRegiao { get; set; }
        public Nullable<int> idPais { get; set; }
    
        public virtual Pais Pais { get; set; }
        public virtual Regiao Regiao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sensor_valor> Sensor_valor { get; set; }
    }
}
